### ISSUE TITLE
Put a range of money from mobs :D

### ISSUE THREAD

**Issue by Gigorahk** [ryandw11/MobHunt#4]
I've been using another plugin named MobHunting but it seems to be giving me errors and server lag. I would like to try yours out and I think it could be improved with a range value like Pig 10:20.

**Comment by ryandw11** [comment]
Ok I'll look into it. Thanks for the suggestion.

**Comment by ryandw11** [comment]
This has been added in version: 1.4.9.2 for 1.10.x. Thank you for your request!
