### ISSUE TITLE
Request: Config for enable/disable monster spawner spawned kills

### ISSUE THREAD

**Issue by fahlur** [ryandw11/MobHunt#5]
Maybe a config option where you can disable gaining reward from monster spawner kills (to limit the chance of farms). 

I can see this by adding a meta tag to the mobs like 'UnaturalSpawn: 1" or something to that effect..

**Comment by ryandw11** [comment]
Thanks for the suggestion.

**Comment by ryandw11** [comment]
Thank you for the request. This has been added into 1.5.2. I hope you enjoy!
